#!/bin/bash -ue
#PBS -q sg8
#PBS -l select=1:ncpus=48:mpiprocs=4:ompthreads=12:ngpus=4
#PBS -l walltime=0:10:0
#PBS -P culb2d@PG22018
#PBS -N culb2d
#PBS -o log/
#PBS -j oe

if [ -n "$PBS_O_WORKDIR" ]; then
    cd $PBS_O_WORKDIR
fi

{ ## global block for `tee <logfile>`

# modules
. /etc/profile.d/modules.sh 
module purge 
module load mpt/2.23-ga cuda/11.0 gnu/7.4.0; export MPI_USE_CUDA=1
module use --append $HOME/ulocal/modulefiles
module load boost # ulocal
module load hdf5/1.8.12

module list 2>&1 
export MPI_DSM_VERBOSE=1
export OMP_NUM_THREADS=12

env

module list 2>&1 

run () {
N=$1
p=$2
beta=$3
daprune=10
o=ruv
d=timer_v2.4.3
iop=$daprune

echo ======================================================
echo start run N=$N daprune=$daprune xyprune=$p beta=$beta
echo ======================================================


#RESULT_DIR=result/$d/observe_$o/xyprune$p
RESULT_DIR=result/$d/observe_$o/ens${N}_xyprune${p}
mkdir -p $RESULT_DIR

# func
run_mpirun() {
    n=$1
    mpirun -np $n omplace run/a.out
}

make clean resultclean

## obs
make clean 
make -j TEST=OBSERVE DA_XYPRUNE=$p IOPRUNE=$iop DAPRUNE=$daprune
run_mpirun 1

## letkf
make clean
make -j TEST=DA_LETKF DA_XYPRUNE=$p DAPRUNE=$daprune IOPRUNE=$iop LETKF_COVINF=$beta
run_mpirun $N
}

# pointwise LETKF
run 4 1 1

} | tee log/timer.txt
